name: Heartbeat Test

on:
  workflow_dispatch: # allows manual trigger
  schedule:
    - cron: '*/10 * * * *' # runs every 10 minutes

jobs:
  heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: npx playwright test
        env:
          LOGIN_USER: ${{ secrets.LOGIN_USER }}
          LOGIN_PASS: ${{ secrets.LOGIN_PASS }}
